# New Data Summary

Recieved new CSV from the YW, it includes the old data and some new data all in one.

Both CSVs prepared with scrubadub for descriptions, default `ReportData` parameters, and the following pipeline:
```python
pipeline: List[Type[Preprocessor]] = [
    DatetimeMapper,
    DescriptionScrubber,
    IncidentTypesProcessor,
    WordCharacterFilter,
    Lowercaser,
]
```

In [1]:
import sys

from os import path

root = path.abspath(path.join(".."))
sys.path.append(root)
pre = path.abspath(path.join(root, "preprocess"))
sys.path.append(pre)

import pandas as pd
from report_data_d import ColName
from report_data import ReportData
old_df = ReportData(out_file_path='./data/data-processed-old.csv').get_processed_data()
new_df = ReportData().get_processed_data()

In [2]:
old_df

,ColName.DT_INC,ColName.LOC,ColName.LOC_DET,ColName.CLI_PRI,ColName.CLI_SEC,ColName.CHI_INV,ColName.N_CLI_INV,ColName.PRO,ColName.CFS,ColName.EMS,...,ColName.RES_SP,ColName.RES_O,ColName.RES_OD,ColName.DT_WRIT,ColName.HOUR_OF_DAY,ColName.MORNING,ColName.AFTERNOON,ColName.EVENING,ColName.NIGHT,ColName.WEEKDAY
0,2019-02-05 18:10:00,YW Providence,Providence,MC,NaN,No,No,Croydon (Community Housing),0.0,1.0,...,0.0,0.0,NaN,2019-02-05 19:21:00,18,0,0,1,0,1
1,2019-02-06 16:00:00,YW Maple,Maple staff office,RT,NaN,No,No,The Maple (Community Housing),0.0,0.0,...,0.0,0.0,NaN,2019-02-06 16:22:00,16,0,1,0,0,1
2,2019-02-07 22:15:00,YW Providence,Providence,SP,NaN,No,Yes,Providence (Community Housing),0.0,0.0,...,0.0,0.0,NaN,2019-02-07 22:47:00,22,0,0,0,1,1
3,2019-02-10 05:05:00,YW Croydon,Main Floor Hallway -Croydon,AO,NaN,No,No,Croydon (Community Housing),0.0,1.0,...,0.0,0.0,NaN,2019-02-10 05:30:00,5,1,0,0,0,0
4,2019-02-10 22:00:00,YW Downtown,417 Client Support Office,DA515,NaN,No,No,Transitional Housing,0.0,1.0,...,0.0,1.0,Assessed client health safety and called EMS,2019-02-10 23:30:00,22,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,2020-04-28 13:00:00,YW Maple,"community housing,",JWI,NaN,No,No,The Maple (Community Housing),0.0,1.0,...,0.0,1.0,Medical,2020-04-28 00:00:00,13,0,1,0,0,1
331,2020-04-28 15:00:00,YW Hub,Emergency Beds Wing,LHS329,NaN,No,No,Transitional Housing,NaN,NaN,...,1.0,0.0,NaN,2020-04-28 16:53:00,15,0,1,0,0,1
332,2020-04-28 17:30:00,YW Providence,Unit 205,N,Z,No,No,Providence (Community Housing),0.0,1.0,...,0.0,0.0,NaN,2020-04-28 19:19:00,17,0,0,1,0,1
333,2020-04-29 13:20:00,In community,Remote - telephone.,D.B.,K.M.,Yes,No,Counselling and Personal Development,1.0,0.0,...,0.0,0.0,NaN,2020-04-29 16:45:00,13,0,1,0,0,1
334,2020-05-02 09:30:00,YW Hub,5th floor,BR,NaN,No,No,Transitional Housing,0.0,1.0,...,0.0,1.0,taken to hospital,2020-05-02 21:40:00,9,1,0,0,0,0

In [3]:
new_df

,ColName.DT_INC,ColName.LOC,ColName.LOC_DET,ColName.CLI_PRI,ColName.CLI_SEC,ColName.CHI_INV,ColName.N_CLI_INV,ColName.PRO,ColName.CFS,ColName.EMS,...,ColName.RES_SP,ColName.RES_O,ColName.RES_OD,ColName.DT_WRIT,ColName.HOUR_OF_DAY,ColName.MORNING,ColName.AFTERNOON,ColName.EVENING,ColName.NIGHT,ColName.WEEKDAY
0,2019-02-05 18:10:00,YW Providence,Providence,MC,NaN,No,No,Croydon (Community Housing),0,1,...,0,0,NaN,2019-02-05 19:21:00,18,0,0,1,0,1
1,2019-02-06 16:00:00,YW Maple,Maple staff office,RT,NaN,No,No,The Maple (Community Housing),0,0,...,0,0,NaN,2019-02-06 16:22:00,16,0,1,0,0,1
2,2019-02-07 22:15:00,YW Providence,Providence,SP,NaN,No,Yes,Providence (Community Housing),0,0,...,0,0,NaN,2019-02-07 22:47:00,22,0,0,0,1,1
3,2019-02-10 05:05:00,YW Croydon,Main Floor Hallway -Croydon,AO,NaN,No,No,Croydon (Community Housing),0,1,...,0,0,NaN,2019-02-10 05:30:00,5,1,0,0,0,0
4,2019-02-10 22:00:00,YW Downtown,417 Client Support Office,DA515,NaN,No,No,Transitional Housing,0,1,...,0,1,Assessed client health safety and called EMS,2019-02-10 23:30:00,22,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,2020-07-22 14:30:00,YW Hub,In the north end of the courtyard,Unsure of name but known to staff as difficult,NaN,No,Yes,Transitional Housing,0,0,...,0,1,Security came to handle then shortly after Fac...,2020-07-22 13:20:00,14,0,1,0,0,1
428,2020-07-23 16:30:00,YW Hub,3rd floor Housing Desk,CW345,NaN,No,No,Transitional Housing,0,0,...,0,0,NaN,2020-07-23 18:00:00,16,0,1,0,0,1
429,2020-07-23 15:50:00,YW Maple,community housing,WE,NaN,No,Yes,The Maple (Community Housing),0,0,...,0,0,NaN,2020-07-24 13:19:00,15,0,1,0,0,1
430,2020-07-24 07:45:00,YW Maple,community housing.,NaN,NaN,No,Yes,The Maple (Community Housing),0,0,...,0,0,NaN,2020-07-24 13:27:00,7,1,0,0,0,1
431,2020-07-20 13:30:00,YW Sheriff King,Over the phone - Intake for DV Group,D,B,Yes,No,Counselling and Personal Development,1,0,...,0,0,NaN,2020-07-28 16:00:00,13,0,1,0,0,1

Looks like there should be 97 new examples.

In [4]:
old_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335 entries, 0 to 334
Data columns (total 36 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ColName.DT_INC       335 non-null    object
 1   ColName.LOC          335 non-null    object
 2   ColName.LOC_DET      335 non-null    object
 3   ColName.CLI_PRI      331 non-null    object
 4   ColName.CLI_SEC      70 non-null     object
 5   ColName.CHI_INV      335 non-null    object
 6   ColName.N_CLI_INV    335 non-null    object
 7   ColName.PRO          335 non-null    object
 8   ColName.CFS          322 non-null    float64
 9   ColName.EMS          322 non-null    float64
 10  ColName.FIRE         322 non-null    float64
 11  ColName.MISC_SERV_F  322 non-null    float64
 12  ColName.DOAP_PACT    322 non-null    float64
 13  ColName.POLICE       322 non-null    float64
 14  ColName.MISC_SERV    31 non-null     object
 15  ColName.INC_T1       335 non-null    object
 16  ColName.INC_T2       255 non-null    object
 17  ColName.DESC         335 non-null    object
 18  ColName.RES_CHI_WF   323 non-null    float64
 19  ColName.RES_EV       323 non-null    float64
 20  ColName.RES_FA       323 non-null    float64
 21  ColName.RES_IPP      323 non-null    float64
 22  ColName.RES_MA       323 non-null    float64
 23  ColName.RES_N        323 non-null    float64
 24  ColName.RES_PB       323 non-null    float64
 25  ColName.RES_SA       323 non-null    float64
 26  ColName.RES_SP       323 non-null    float64
 27  ColName.RES_O        323 non-null    float64
 28  ColName.RES_OD       87 non-null     object
 29  ColName.DT_WRIT      335 non-null    object
 30  ColName.HOUR_OF_DAY  335 non-null    int64
 31  ColName.MORNING      335 non-null    int64
 32  ColName.AFTERNOON    335 non-null    int64
 33  ColName.EVENING      335 non-null    int64
 34  ColName.NIGHT        335 non-null    int64
 35  ColName.WEEKDAY      335 non-null    int64
dtypes: float64(16), int64(6), object(14)
memory usage: 94.3+ KB

Some NaNs in columns like CFS

In [5]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 36 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ColName.DT_INC       432 non-null    object
 1   ColName.LOC          432 non-null    object
 2   ColName.LOC_DET      432 non-null    object
 3   ColName.CLI_PRI      426 non-null    object
 4   ColName.CLI_SEC      95 non-null     object
 5   ColName.CHI_INV      432 non-null    object
 6   ColName.N_CLI_INV    432 non-null    object
 7   ColName.PRO          432 non-null    object
 8   ColName.CFS          432 non-null    int64
 9   ColName.EMS          432 non-null    int64
 10  ColName.FIRE         432 non-null    int64
 11  ColName.MISC_SERV_F  432 non-null    int64
 12  ColName.DOAP_PACT    432 non-null    int64
 13  ColName.POLICE       432 non-null    int64
 14  ColName.MISC_SERV    61 non-null     object
 15  ColName.INC_T1       432 non-null    object
 16  ColName.INC_T2       323 non-null    object
 17  ColName.DESC         432 non-null    object
 18  ColName.RES_CHI_WF   432 non-null    int64
 19  ColName.RES_EV       432 non-null    int64
 20  ColName.RES_FA       432 non-null    int64
 21  ColName.RES_IPP      432 non-null    int64
 22  ColName.RES_MA       432 non-null    int64
 23  ColName.RES_N        432 non-null    int64
 24  ColName.RES_PB       432 non-null    int64
 25  ColName.RES_SA       432 non-null    int64
 26  ColName.RES_SP       432 non-null    int64
 27  ColName.RES_O        432 non-null    int64
 28  ColName.RES_OD       111 non-null    object
 29  ColName.DT_WRIT      432 non-null    object
 30  ColName.HOUR_OF_DAY  432 non-null    int64
 31  ColName.MORNING      432 non-null    int64
 32  ColName.AFTERNOON    432 non-null    int64
 33  ColName.EVENING      432 non-null    int64
 34  ColName.NIGHT        432 non-null    int64
 35  ColName.WEEKDAY      432 non-null    int64
dtypes: int64(22), object(14)
memory usage: 121.6+ KB

Columns which had NaNs in the old no longer have NaNs

## New Data

Get the differing rows from the new CSV.

In [6]:
merged = old_df.merge(new_df, how='outer', indicator=True)
new_only = merged[lambda x: x['_merge']=='right_only']
new_only

,ColName.DT_INC,ColName.LOC,ColName.LOC_DET,ColName.CLI_PRI,ColName.CLI_SEC,ColName.CHI_INV,ColName.N_CLI_INV,ColName.PRO,ColName.CFS,ColName.EMS,...,ColName.RES_O,ColName.RES_OD,ColName.DT_WRIT,ColName.HOUR_OF_DAY,ColName.MORNING,ColName.AFTERNOON,ColName.EVENING,ColName.NIGHT,ColName.WEEKDAY,_merge
335,2019-02-26 23:50:00,YW Maple,unit 405,L.C.,B.S.,No,No,The Maple (Community Housing),0.0,0.0,...,0.0,NaN,2019-02-26 00:35:00,23,0,0,0,1,1,right_only
336,2019-03-07 11:45:00,YW Downtown,5th floor lounge,DA515,NaN,No,No,Transitional Housing,0.0,1.0,...,0.0,NaN,2019-03-07 14:13:00,11,1,0,0,0,1,right_only
337,2019-03-25 08:00:00,YW Providence,2nd floor,Amanda,Roger,No,Yes,Providence (Community Housing),0.0,0.0,...,1.0,Police report to be completed. Debrief complet...,2019-03-25 08:00:00,8,1,0,0,0,1,right_only
338,2019-03-26 23:30:00,YW Providence,Unit 306,A,B,No,No,Providence (Community Housing),0.0,1.0,...,0.0,NaN,2019-03-26 23:55:00,23,0,0,0,1,1,right_only
339,2019-04-27 18:35:00,YW Maple,Maple,WE,"AN, LC",No,No,The Maple (Community Housing),0.0,0.0,...,0.0,NaN,2019-04-27 20:30:00,18,0,0,1,0,0,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,2020-07-22 14:30:00,YW Hub,In the north end of the courtyard,Unsure of name but known to staff as difficult,NaN,No,Yes,Transitional Housing,0.0,0.0,...,1.0,Security came to handle then shortly after Fac...,2020-07-22 13:20:00,14,0,1,0,0,1,right_only
454,2020-07-23 16:30:00,YW Hub,3rd floor Housing Desk,CW345,NaN,No,No,Transitional Housing,0.0,0.0,...,0.0,NaN,2020-07-23 18:00:00,16,0,1,0,0,1,right_only
455,2020-07-23 15:50:00,YW Maple,community housing,WE,NaN,No,Yes,The Maple (Community Housing),0.0,0.0,...,0.0,NaN,2020-07-24 13:19:00,15,0,1,0,0,1,right_only
456,2020-07-24 07:45:00,YW Maple,community housing.,NaN,NaN,No,Yes,The Maple (Community Housing),0.0,0.0,...,0.0,NaN,2020-07-24 13:27:00,7,1,0,0,0,1,right_only
457,2020-07-20 13:30:00,YW Sheriff King,Over the phone - Intake for DV Group,D,B,Yes,No,Counselling and Personal Development,1.0,0.0,...,0.0,NaN,2020-07-28 16:00:00,13,0,1,0,0,1,right_only

26 more rows than expected, some rows which should be the same are different.

In [7]:
old_only = merged[lambda x: x['_merge']=='left_only']
old_only

,ColName.DT_INC,ColName.LOC,ColName.LOC_DET,ColName.CLI_PRI,ColName.CLI_SEC,ColName.CHI_INV,ColName.N_CLI_INV,ColName.PRO,ColName.CFS,ColName.EMS,...,ColName.RES_O,ColName.RES_OD,ColName.DT_WRIT,ColName.HOUR_OF_DAY,ColName.MORNING,ColName.AFTERNOON,ColName.EVENING,ColName.NIGHT,ColName.WEEKDAY,_merge
19,2019-02-26 23:50:00,YW Maple,unit 405,L.C.,B.S.,No,No,The Maple (Community Housing),NaN,NaN,...,0.0,NaN,2019-02-26 00:35:00,23,0,0,0,1,1,left_only
31,2019-03-07 11:45:00,YW Downtown,5th floor lounge,DA515,NaN,No,No,Transitional Housing,0.0,1.0,...,NaN,NaN,2019-03-07 14:13:00,11,1,0,0,0,1,left_only
40,2019-03-25 08:00:00,YW Providence,2nd floor,Amanda,Roger,No,Yes,Providence (Community Housing),NaN,NaN,...,1.0,Police report to be completed. Debrief complet...,2019-03-25 08:00:00,8,1,0,0,0,1,left_only
42,2019-03-26 23:30:00,YW Providence,Unit 306,A,B,No,No,Providence (Community Housing),0.0,1.0,...,NaN,NaN,2019-03-26 23:55:00,23,0,0,0,1,1,left_only
88,2019-04-27 18:35:00,YW Maple,Maple,WE,"AN, LC",No,No,The Maple (Community Housing),NaN,NaN,...,0.0,NaN,2019-04-27 20:30:00,18,0,0,1,0,0,left_only
91,2019-04-28 07:00:00,YW Sheriff King,Shelter,A.O,NaN,No,No,Sheriff King Home,0.0,0.0,...,NaN,NaN,2019-04-28 00:00:00,7,1,0,0,0,0,left_only
97,2019-05-03 16:10:00,YW Downtown,419/421 Washroom,LO421,NaN,No,No,Transitional Housing,0.0,1.0,...,NaN,NaN,2019-05-03 17:00:00,16,0,1,0,0,1,left_only
117,2019-05-28 17:12:00,YW Providence,4th floor office,MMT,NaN,No,No,Providence (Community Housing),0.0,1.0,...,NaN,NaN,2019-05-28 17:15:00,17,0,0,1,0,1,left_only
125,2019-06-14 15:05:00,YW Downtown,Room 515,DA,NaN,No,No,Transitional Housing,0.0,1.0,...,NaN,NaN,2019-06-14 16:30:00,15,0,1,0,0,1,left_only
182,2019-09-10 21:40:00,YW Hub,Housing Intake Reception,ER 431,NaN,No,No,Transitional Housing,0.0,0.0,...,NaN,NaN,2019-09-10 22:08:00,21,0,0,0,1,1,left_only
187,2019-09-16 21:30:00,YW Maple,back parking lot,DD,NaN,No,Yes,The Maple (Community Housing),NaN,NaN,...,0.0,NaN,2019-09-16 22:15:00,21,0,0,0,1,1,left_only
204,2019-10-11 09:15:00,YW Hub,3rd floor,DD,NaN,No,No,Transitional Housing,0.0,1.0,...,NaN,NaN,2019-10-11 10:09:00,9,1,0,0,0,1,left_only
215,2019-10-25 13:08:00,YW Maple,Main office,MWB,NaN,No,No,The Maple (Community Housing),NaN,NaN,...,0.0,NaN,2019-10-25 14:39:00,13,0,1,0,0,1,left_only
227,2019-11-09 12:50:00,YW Hub,3rd floor,VC,NaN,No,No,Transitional Housing,0.0,1.0,...,NaN,NaN,2019-11-09 13:23:00,12,0,1,0,0,0,left_only
239,2019-12-03 20:00:00,YW Hub,Room 234,L,C,No,No,Counselling and Personal Development,NaN,NaN,...,1.0,Attempted to de-escalate situation; client inv...,2019-12-04 16:45:00,20,0,0,1,0,1,left_only
249,2019-12-19 07:00:00,YW Maple,Maple main office and unit 405,DD,NaN,No,No,The Maple (Community Housing),0.0,1.0,...,NaN,NaN,2019-12-19 09:10:00,7,1,0,0,0,1,left_only
258,2019-12-27 07:00:00,YW Hub,Transitional Housing 3rd Floor,MLL372,NaN,No,Yes,Transitional Housing,NaN,NaN,...,0.0,NaN,2019-12-27 09:15:00,7,1,0,0,0,1,left_only
259,2019-12-30 10:00:00,YW Maple,Main Office,JL 406,NaN,No,No,The Maple (Community Housing),0.0,1.0,...,NaN,NaN,2019-12-30 10:30:00,10,1,0,0,0,1,left_only
261,2020-01-07 12:15:00,YW Providence,3rd floor hallway outside of unit,TE,NaN,No,Yes,Providence (Community Housing),NaN,NaN,...,1.0,Intervention,2020-01-07 13:53:00,12,0,1,0,0,1,left_only
302,2020-03-18 08:30:00,YW Providence,main floor hallway,BD,NaN,No,No,Providence (Community Housing),NaN,NaN,...,0.0,NaN,2020-03-18 12:27:00,8,1,0,0,0,1,left_only
303,2020-03-18 08:30:00,YW Providence,"main floor hallway, basement hallway, communit...",BD,NaN,No,No,Providence (Community Housing),NaN,NaN,...,0.0,NaN,2020-03-18 13:14:00,8,1,0,0,0,1,left_only
304,2020-03-19 20:30:00,YW Maple,Unit 205,SSC,NaN,No,No,The Maple (Community Housing),0.0,1.0,...,NaN,NaN,2020-03-20 08:00:00,20,0,0,1,0,1,left_only
313,2020-04-07 16:05:00,YW Hub,4th floor - Neighbourhood 4b,SS 464,NaN,No,No,Transitional Housing,NaN,NaN,...,0.0,NaN,2020-04-09 11:50:00,16,0,1,0,0,1,left_only
320,2020-04-22 14:30:00,YW Maple,Maple,AN,NaN,No,No,The Maple (Community Housing),NaN,NaN,...,0.0,NaN,2020-04-22 15:55:00,14,0,1,0,0,1,left_only
331,2020-04-28 15:00:00,YW Hub,Emergency Beds Wing,LHS329,NaN,No,No,Transitional Housing,NaN,NaN,...,0.0,NaN,2020-04-28 16:53:00,15,0,1,0,0,1,left_only
332,2020-04-28 17:30:00,YW Providence,Unit 205,N,Z,No,No,Providence (Community Housing),0.0,1.0,...,0.0,NaN,2020-04-28 19:19:00,17,0,0,1,0,1,left_only

Compare the differing rows with their counterparts.

In [8]:
o = old_only.drop(columns='_merge')
for i, row in o.iterrows():
    print(i)
    print(new_df.loc[i].compare(row))

19
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
31
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
40
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
42
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
88
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
91
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
97
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
117
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
125
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
182
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
187
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
204
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
215
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
227
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
239
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
249
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
258
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
259
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
261
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
302
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
303
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
304
                   self other
ColName.RES_CHI_WF    0   NaN
ColName.RES_EV        0   NaN
ColName.RES_FA        0   NaN
ColName.RES_IPP       0   NaN
ColName.RES_MA        0   NaN
ColName.RES_N         0   NaN
ColName.RES_PB        0   NaN
ColName.RES_SA        0   NaN
ColName.RES_SP        0   NaN
ColName.RES_O         0   NaN
313
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
320
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
331
                    self other
ColName.CFS            0   NaN
ColName.EMS            0   NaN
ColName.FIRE           0   NaN
ColName.MISC_SERV_F    0   NaN
ColName.DOAP_PACT      0   NaN
ColName.POLICE         0   NaN
332
                self other
ColName.CLI_PRI   NZ     N
ColName.CLI_SEC  NaN     Z

Just the extra NaN's in the old data are replaced correctly with zeroes.

There's one row where previously it seems the client initials where split between the primary and secondary columns but now they are in just the primary, which is probably desirable.

In summary, we can just keep the new CSV and discard the old.

## Incident Types

Check for new incident types.

In [45]:
new = set([*new_df[ColName.INC_T1], *new_df[ColName.INC_T2]])
old = set([*old_df[ColName.INC_T1], *old_df[ColName.INC_T2]])
print(old - new)
print(new - old)

set()
{'Client missing', 'Child abandonment', 'Refusal to isolate for covid-19', 'Suspicion/allegation of child abuse - child is not a client', 'COVID-19 Confirmed'}

One entirely new type added: 'Refusal to isolate for covid-19'.

Examples of known types which previously lacked data added.

Calculate additional incident types examples provided in the new data.

In [43]:
def get_inc_counts(colname: ColName):
    old = old_df[colname].value_counts()
    new = new_df[colname].value_counts()
    old = old.reindex(old.index.union(new.index)).fillna(0)
    return old, new

old1, new1 = get_inc_counts(ColName.INC_T1)
print((new1 - old1))

COVID-19 Confirmed                                              3.0
Child abandonment                                               1.0
Client aggression towards another person                        4.0
Client aggression towards property                              6.0
Client death (onsite)                                           0.0
Client missing                                                  1.0
Concern for welfare of a child                                  4.0
Exposure                                                        1.0
Homicide (Threat or attempt)                                    0.0
Illegal activity on premises                                    0.0
Injury                                                         10.0
Medical emergency                                              26.0
Mental health emergency                                        13.0
Other                                                          18.0
Security concern                                                4.0
Suicide attempt                                                 1.0
Suspicion/allegation of abuse towards or against client         4.0
Suspicion/allegation of child abuse - child is not a client     1.0
Name: ColName.INC_T1, dtype: float64

In [44]:
old2, new2 = get_inc_counts(ColName.INC_T2)
print((new2 - old2))

Client aggression towards another person                    4.0
Client aggression towards property                          0.0
Concern for welfare of a child                              1.0
Exposure                                                    0.0
Homicide (Threat or attempt)                                0.0
Illegal activity on premises                                1.0
Injury                                                      2.0
Medical emergency                                           2.0
Mental health emergency                                     1.0
Other                                                      56.0
Refusal to isolate for covid-19                             1.0
Security concern                                            0.0
Suicide attempt                                             0.0
Suspicion/allegation of abuse towards or against client     0.0
Name: ColName.INC_T2, dtype: float64